-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Servidor: sql206.infinityfree.com
-- Tiempo de generación: 14-06-2025 a las 21:53:25
-- Versión del servidor: 10.6.19-MariaDB
-- Versión de PHP: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `if0_38870682_minizooxxiii`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `especies`
--

CREATE TABLE `especies` (
  `id` int(11) NOT NULL,
  `place` int(11) DEFAULT NULL,
  `name` varchar(191) NOT NULL,
  `alt_name` varchar(191) DEFAULT NULL,
  `scient_name` varchar(191) DEFAULT NULL,
  `img` varchar(255) NOT NULL,
  `specie_order` varchar(100) DEFAULT NULL,
  `family` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `ecology` text DEFAULT NULL,
  `distribution` text DEFAULT NULL,
  `qr_img` varchar(255) NOT NULL,
  `qr_url` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `especies`
--

INSERT INTO `especies` (`id`, `place`, `name`, `alt_name`, `scient_name`, `img`, `specie_order`, `family`, `description`, `ecology`, `distribution`, `qr_img`, `qr_url`) VALUES
(36, 8, 'Yacaré negro', 'Jakare hu', 'Caiman yacaré', 'img/yacare_negro.jpg', 'Crocodilia', 'Alligatoridae', 'Es un reptil acuático. Los ojos y las fosas nasales están proyectadas hacia arriba sobre el dorso de la cabeza.\\r\\nLa cola es aplastada posee cretas denticuladas y filas transversales de escudos gruesos al dorso, lo que indica que es un yacaré. El color del dorso suele ser color café obscuro a negro salpicado de blanco, principalmente en los juveniles pero varía sobre todo cuando están soleándose con la piel seca la parte ventral es amarilla o crema una características constantes son las manchas negras algo redondeada sobre la mandíbula inferior clara el jacaré adulto mide 1,30 m, pero se han observado individuos de 2.50 m', 'Se encuentran en ríos, esteros, estanques y lugares donde hay agua todo el año. Su dieta consiste en peces, caracoles, cangrejos e insectos. El joven consume más insectos y el adulto peces. La época de reproducción es entre noviembre a febrero y las hembras depositan sus huevos entre la última semana de diciembre y la primera de febrero, dentro de unos montículos hechos de material vegetal. En una nidada, deposita ente 21 a 38 huevos. La hembra alcanza la madurez sexual a los 4 años de edad o cuando miden aproximadamente entre 65 y 70 cm.', 'Se encuentra en todo el Chaco Paraguayo, excepto en aquellos sitios que carecen de cuerpos de agua permanente. Fue colectada en algunos Departamentos de la Región Oriental.', '', ''),
(37, NULL, 'Koati', 'Pizotes', 'Nasua', 'img/coati.jpg', 'Carnivora', 'Procyonidae', 'El dorso es de color pardo amarillento a marrón oscuro, casi negro, mientras que la zona ventral puede ser blanquecina o anaranjada fuerte, el pelo es espeso y opaco. La cabeza es triangular y el hocico largo, la cola es marrón con anillos amarillentos característicos, generalmente la mantiene levantada en forma perpendicular al cuerpo. Posee orejas pequeñas y redondeadas con pelos blancos en el borde interior.\\r\\nLas extremidades son oscuras con uñas largas y fuertes. El macho es más robusto que la hembra y posee los caninos más desarrollados. El largo del cuerpo es de 410 a 670 mm el largo de la cola es de 320 a 690 mm y pesa 3,5 a 6 Kg.', 'Se encuentra en diferentes tipos de vegetación, desde bosque espinoso achaparrado hasta bosque húmedo tropical. Es omnívora, come frutas y es depredadora oportunista. Es diurna, terrestre, trepadora y arborícola, la hembra forma grupos de hasta 30 individuos y se desplaza formando tropas, pero el macho es a menudo solitario. Las crías nacen después de los 77 días de gestación en un nido construido en los árboles por la hembra. La camada varia de una a seis crías. Durante la primera etapa de vida, las crías permanecen en el nido, pero luego de las dos o tres semanas\\r\\ncomienzan a acompañar a su madre, que se une a otras hembras con crías.', 'En Paraguay se distribuye en ambas regiones, pero es escasa en el Chaco Seco.', '', ''),
(38, 4, 'Anaconda', 'Kuriju', 'Eunectes murinus', 'img/anaconda.jpg', 'Squamata', 'Boidae', 'Es la serpiente más grande del Chaco. Tiene una fila de manchas obscuras a lo largo del dorso, de color café o negro, más ancha que larga y de forma ovalada o irregular. Sobre la cabeza tiene tres listas obscuras, el color del fondo es amarillo a marrón oliva. A ambos lados presentan manchas obscuras que se suelen juntar formando un anillo.\\r\\nLas escamas ventrales son amarillas con pequeñas manchas negras las que se unen formando lineas. \\r\\nMide unos 4 metros o más de largo.', 'Es una cazadora acuática. Podemos verlas en los humedales, cerca de los ríos o sobre los pastos tomando sol. Se alimenta de pequeños mamíferos y aves. En cautiverio la hembra ha tenido entre 12 a 22 crías que miden entre 56 y 66 cm al nacer, llegan a medir hasta 1,8 m. y a pesar 2,6 kg a los 2 años de edad.', 'Habita en la cuenca del Paraguay y sus afluentes, tanto en la Región Occidental y algunos departamentos de la región', '', ''),
(39, NULL, 'Jaguar', 'Jaguarete', 'Panthera Onca', 'img/Jaguar.png', 'Carnívora', 'Felidae', 'Es el felino más grande de América. Su pelaje es amarillo leonado con manchas negras en forma de rosetas, aunque también existen ejemplares completamente negros (melánicos). Tiene un cuerpo robusto, patas grandes y cola corta. Los machos son más grandes y de coloración más intensa que las hembras.', 'Habita en una variedad de ambientes, principalmente bosques tropicales, pero también zonas áridas y otras formaciones boscosas. Su dieta incluye mamíferos medianos y grandes como venados, agutíes, pacas, puercoespines y víboras. La gestación dura entre 95 y 96 días, y las crías nacen con un peso de 226 a 453 gramos. La hembra alcanza la madurez sexual a los 2,5 años y el macho a los 3 años.', 'Se encuentra en ambas regiones del país. Sin embargo, en la Región Oriental sus poblaciones han disminuido considerablemente debido a la pérdida de hábitat y otras amenazas.', '', ''),
(40, NULL, 'Lechuza de Campanario', 'Suindá', 'Tyto alba', 'img/Lechuza.png', 'Strigiformes', 'Tytonidae', 'Se distingue por su característico disco facial blanco en forma de corazón, rodeado por un borde oscuro. Su dorso presenta un tono gris salpicado de ocre y blanco, mientras que la parte ventral es ocre con leves manchas. Sus largas patas, completamente emplumadas, son de color blanco. De hábitos nocturnos, se alimenta principalmente de roedores y otros pequeños vertebrados. Alcanza una longitud aproximada de 36 cm.', 'Es una especie adaptada a vivir en zonas abiertas, y suele encontrarse en áreas rurales y alrededores de poblados, donde encuentra alimento con facilidad. Cumple un rol ecológico importante como controladora de poblaciones de roedores.', 'Está presente tanto en la Región Oriental como en la Región Occidental del país, aunque es una especie de observación poco frecuente.', '', ''),
(41, NULL, 'Iguana Negra', 'Tejú Hu', 'Salvator merianae', 'img/iguana.jpg', 'Squamata', 'Iguanidae', 'Es uno de los lagartos más grandes de su género. Los machos pueden alcanzar hasta 1,3 metros de longitud, y las hembras hasta 1 metro. Tiene un cuerpo largo y robusto, comprimido lateralmente, con una cabeza alargada y aplanada en la parte frontal. Su piel está cubierta de pequeñas escamas quilladas, especialmente en la cola. Estas escamas, junto con la capacidad de cambiar de color, le permiten camuflarse en su entorno.', 'Es una especie diurna y principalmente herbívora. Se alimenta de flores, hojas, tallos y frutas, aunque también puede consumir huevos de aves y pequeños vertebrados como ratones. Cumple un rol ecológico importante en la dispersión de semillas y el control de pequeñas poblaciones animales.', 'La iguana negra se encuentra en regiones de Centroamérica y América del Sur. En Paraguay, está presente principalmente en zonas cálidas y secas del Chaco, donde habita selvas bajas, matorrales y áreas rocosas. Aunque no es común, se puede encontrar en determinadas regiones del país.', '', ''),
(42, NULL, 'El Mono Nocturno', 'Ka´i Pyhare', 'Aotus azarae', 'img/Mono.jpg', 'Primates', 'Cebidae', 'Es una especie de primate perteneciente al género Aotus, tiene un tamaño corporal pequeño a mediano entre 25 a 40 centímetros, sin incluir la cola. Tiene un pelaje denso, de color marrón grisáceo o amarillento, con el vientre más claro. Tiene ojos grandes y redondeados, adaptados a la visión nocturna. Un rostro oscuro con marcas faciales características y una franja blanca entre los ojos.', 'Habita en sabanas inundables con palmares. Es nocturno y se lo ha encontrado activo en días nublados en Paraguay. Utiliza la orina como medio, de comunicación sexual. Su dormidero se encuentra a una altura promedio de 11 m. Se alimenta de frutas, hojas, flores, insectos y pequeños vertebrados. Forma parejas monógamas y estables. La hembra da a luz 1 cría única entre agosto y octubre. El periodo de gestación es de 150 a 153 días. La cría permanece con los padres hasta los 2 años de vida.', 'En Paraguay, es característico en la Región Occidental. En la Región Oriental hay reportes de su presencia en el Departamento de Concepción. También es encontrado en países como Bolivia, Argentina y Brasil.', '', ''),
(43, NULL, 'Tortuga de Laguna', NULL, 'Phrynops hilarii', 'img/Tortuga.jpg', 'Testudines', 'Chelidae', 'Son tortugas acuáticas con caparazones obscuros relativamente planos, y de cuello largo y con la cabeza visiblemente más ancha que el cuello. Carecen de partes movedizas del plastrón. Encogen la cabeza lateralmente bajo el caparazón; en esta posición un lado de la cabeza y el cuello permanecen expuestos. Las partes dorsales de la cabeza y las patas son oliva, grises o negras. Pero la mitad inferior de la cabeza y parte del plastrón, especialmente los bordes, pueden ser blancuzcos o amarillos. El caparazón mide de 20 a 40 centímetros.', 'Vive en cuerpos de agua dulce como lagunas, arroyos, ríos de corriente lenta, chacras y humedales. Es una especie omnívora, aunque tiene un comportamiento principalmente carnívoro, su dieta varía según su edad, los juveniles tienden a ser más carnívoros y los adultos incorporan más vegetales. Tiene un comportamiento diurno, con actividad principalmente de día. Realiza termorregulación mediante la exposición al sol. La época reproductiva varía según la región, pero generalmente ocurre en primavera verano, las hembras depositan entre 9 y 30 huevos en nidos excavados en tierra húmeda, la incubación puede durar de 4 a 6 meses, dependiendo de la temperatura.', 'En el Paraguay se encuentra principalmente en la región oriental, en los departamentos de Itapuá, Alto Paraná, Caazapá y central. Habita por ríos de corriente lenta, arroyos o lagunas, en esteros y bañados con vegetación acuática y en áreas pantanosa y canales artificiales. También es encontrados en otros países como Argentina, Uruguay, Brasil y Bolivia ', '', ''),
(44, NULL, 'Huron Mayor', NULL, 'Eira barbara', 'img/HuronMayor.jpg', 'Carnívoro', 'Mustelidae', 'La longitud del cuerpo en los machos alcanza entre los 98 cm a 1.20 metros (contando la cola de unos 25 a 45 cm) y su peso es de 5 a 7 kg (con un promedio de 5 kg). Los machos son un 30% más grandes que las hembras. La cabeza es ancha y de tamaño proporcionalmente grande con relación al cuerpo, en comparación con otros mustélidos. Las patas son relativamente largas, delgadas y con garras fuertes. El cuerpo es musculoso y esbelto, con la espalda ligeramente jorobada. Las orejas son pequeñas y redondeadas, del mismo color que la cabeza y no sobresalen por encima de la coronilla. El manto es suave de pelo corto y de color sepia, negro o castaño uniforme. Los jóvenes son completamente negros, a veces con un parche blanco en la garganta, la cabeza blanca o una franja medio dorsal oscura que se extiende hasta la cola.', ' Habita en bosques de galería en sectores bien arbolados. Es excelente trepador, es frecuentemente visto en lo alto de los árboles, predominantemente frugívora, aunque también puede comportarse cómo como depredadora activa. Entre sus presas también incluye a conejos, aves, cuervos y consume miel. Es activa de día y de noche, pero principalmente en el día, se la encuentra solitaria o en grupos familiares. La madurez sexual de la hembra se presenta antes de los 2 años. El periodo de gestación varia entre 63 a 70 días. La camada es de 2 individuos por parición. El peso al nacimiento es de 100 gramos.', 'En el Paraguay se encuentra principalmente en la región oriental, en bosques del Alto Paraná y departamentos como Canindeyú, Caaguazú, San Pedro, Itapúa y Guairá. También es encontrados en otros países como Brasil, Colombia, Perú, Ecuador, Panamá y Costa Rica', '', ''),
(66, NULL, 'Tucán Grande', 'Tukã guasu', 'Ramphastos ambiguus', 'img/Tucan_Grande.jpg', 'Piciformes', 'Ramphastidae', 'Mide entre 53 y 56 cm de longitud y pesa entre 620 y 740 g. Su plumaje es principalmente negro con las puntas marrón desde la corona hasta la parte alta de la espalda; las plumas encima de la cola son de color crema; debajo de la cola de color rojo; pecho rojo. Pico de aproximadamente 18 cm de largo, un poco más corto en la hembra, con una línea negra alrededor de la base, verde viche o amarillento en el culmen haciéndose más ancho distalmente, presenta un triángulo negruzco sobre el resto de la maxila y sobre la mandíbula, a veces castaño cerca de la base. La piel de la cara es azul, verde pálido, o verde amarillento', 'Son muy sociables. Rara vez se les encuentra solos y permanecen en pequeños grupos con una estructura familiar. Su dieta es mixta, proporción principalmente frutas. También se alimenta de insectos y de algunos vertebrados como serpientes, lagartijas, pequeñas aves o mamíferos y roba huevos. Se reproduce entre marzo y julio. Construye el nido en una cavidad natural de madera, a una altura entre 7 y 27 m del suelo; la entrada es pequeña y apenas deja pasar las aves. La hembra pone de 2 a 4 huevos blancos y ambos padres incuban, alimentan a los polluelos y defienden el nido. La incubación dura 16 días y los polluelos abandonan el nido después de 47 días de nacidos.', 'En Paraguay, habita principalmente en zonas del Bosque Atlántico del Alto Paraná, aunque también puede encontrarse en bordes de bosques y pastizales húmedos. También es encontrado en países como Brasil, Bolivia, Argentina, Uruguay, Peru  y  Guayanas.', '', ''),
(45, 12, 'Loro Hablador ', 'Karau', 'Amazona aestiva xanthopteryx', 'img/loro.jpg', 'Psittaciformes', 'Psittacidae', 'Coloración general verde. Frente celeste. Corona, lados de la cara, borde anterior de las alas y plumas en los muslos, amarillos. Las plumas del cuello posterior y en la parte dorsal con una franja terminal negra, más intensa que la que presenta en los lados del cuello y partes ventrales. Primera primaria con la barba externa azul y negra, la barba interna negra, las demás con la base de la barba externa verde y azul hacia la punta; barbas internas negras. Secundarias con la base de la barba externa verde, luego rojo y verde. La lámina interna negra, excepto la punta que es verde. Cola corta, rectangular, con las plumas exteriores verdes en la base de la barba externa y amarillo verdoso hacia la punta, la barba interna roja en la base, verde oscuro y verde amarillento hacia el ápice. Centrales verdes oscuras con ápice verde amarillento.', 'Vive en selvas y bosques tropicales y subtropicales de América del Sur. Prefiere áreas con vegetación densa, donde puede encontrar cavidades en árboles para anidar y suficiente alimento, como frutas y semillas. Durante la temporada de cría, estas aves buscan cavidades en árboles maduros para anidar, prefiriendo aquellas con buen aislamiento térmico y entradas elevadas. Su tamaño de puesta promedio es de 3.7 huevos, aunque puede variar según la región.', 'En el Paraguay es más notable en bosques subtropicales y zonas de transición. Se encuentra en regiones como el Chaco paraguayo, el Bosque Atlántico y áreas de selvas de galería. Cuenta con una distribución amplia en América del Sur, abarcando regiones de Brasil, Bolivia, Paraguay y Argentina. Se encuentra principalmente en selvas y bosques subtropicales.', '', ''),
(47, NULL, 'Capibara', 'Carpincho', 'Hydrochoerus hydrochaeris', 'img/capibara_que_es_donde_vive_y_que_come_4037_orig.jpg', 'Roedores', 'Hydrochoridae', 'Tiene un cuerpo pesado en forma de barril y una cabeza pequeña, con un pelaje pardo rojizo en la parte superior del cuerpo que se vuelve pardo amarillo. Puede crecer hasta 1,30 m de largo y llegar a pesar 65 kg. Presenta pies ligeramente palmeados, y de manera similar a otros cávidos, carece de cola y cuenta con veinte dientes. Sus patas posteriores son algo más largas que las anteriores, y los hocicos son romos, con ojos, narinas y orejas en la parte superior de la cabeza. Las hembras son ligeramente más pesadas que los machos.', 'La ecología del capibara o  se centra en su papel como herbívoro semiacuático en ecosistemas de humedales y sabanas inundables en Sudamérica.', 'Su enorme área de distribución comprende casi toda Sudamérica al este de los Andes en las cuencas del río Orinoco, del Amazonas y del Río de la Plata; cubriendo desde el este de Venezuela y la Guyana hasta Uruguay, Paraguay y en gran parte del norte de Argentina, mayormente en la provincia de Corrientes.[', '', ''),
(48, NULL, 'Armadillo', 'Tatú', 'Dasypodidae', 'img/images.jpeg', 'Testudines', 'Mamíferos placentarios', 'Los armadillos son mamíferos fáciles de reconocer, distinguibles por tener una armadura formada por placas óseas cubiertas por escudos córneos que les sirven como protección, y que en algunos géneros permiten al animal enrollarse en forma de bola.', 'Los armadillos viven en hábitats templados y cálidos, incluyendo selvas tropicales, pastizales y semidesiertos', 'Se encuentran exclusivamente en el Nuevo Mundo, desde el centro de los Estados Unidos hasta el Cabo de Hornos en el extremo sur de Sudamérica', '', ''),
(50, 13, 'Papagayo Azul', 'Guacamayo jacinto', 'Anodorhynchus hyacinthinus', 'img/papagayosAzules.jpg', 'Psittaciformes ', 'Loros', 'Estas aves crecen hasta alcanzar un tamaño medio de unos 70 cm de longitud (pudiendo alcanzar 105 cm), con una envergadura de 120 a 140 cm y un peso de 1,5 a 1,7 kg. Su pico es el más fuerte de todas las aves, fundamental para alimentarse con nueces y semillas duras. Su pico también les permite romper nueces de coco, madera y otras materias vegetales', 'El papagayo azul es una de las especies de guacamayos más grandes del mundo. Su dieta se basa principalmente en nueces de palmas, como las del Attalea phalerata y Acrocomia aculeata. Utiliza su pico extremadamente fuerte para romper cáscaras muy duras.', ' Sudamérica: en el sur de Brasil, en el este de Bolivia y en el nordeste de Paraguay.', '', ''),
(51, 12, 'Cotorrita', 'Cotorra Monje', 'Myiopsitta monachus', 'img/images (2).jpeg', 'Psittaciformes', 'Psittacidae', 'Es de tamaño pequeño, de entre 28 y 31 cm de largo,[7]? y con un peso de entre 120 y 140 g.[8]? Su plumaje es de un verde brillante, con las alas verdes azuladas vistosas al momento de volar; la frente, mejillas, garganta, pecho y vientre son grises claros. Su cola es larga y puntiaguda, de color verde, como el dorso; el pico es ocre y las patas son grisáceas.', 'Es una especie muy social, vive en grandes colonias.\\r\\n\\r\\nConstruyen nidos comunales muy elaborados, únicos entre los loros.\\r\\n\\r\\nSe alimentan de semillas, frutas, hojas y cultivos agrícolas.\\r\\n\\r\\nSon aves muy adaptables y pueden vivir en zonas urbanas.', 'Originaria del centro y sur de Sudamérica: Argentina, Paraguay, Uruguay, Bolivia y sur de Brasil.', '', ''),
(52, NULL, 'Pecarí de labios blancos', NULL, 'Tayassu pecari', 'img/Pecari.jpg', 'Artiodactyla', 'Tayassuidae', 'El pecarí de labios blancos tiene una longitud de 90 a 130 cm. y una altura de 50 a 60 cm, el peso de los machos adultos fluctúa de 36 a 42 kg. y las hembras adultas entre 34 y 45 kg, posee una cabeza grande y de forma triangular, con una cara plana, el cuello es corto, su cuerpo es compacto y en forma de barril; los ojos son pequeños con escasa visión, pero su magnífico olfato  compensa este déficit. Su piel está cubierta de cerdas largas en \\r\\nla región dorsal y cortas en los flancos, estas cerdas que varían del rojizo al negro alcanzan un tamaño de \\r\\n28 a 115 mm. en las partes ventrales y laterales de la mandíbula, del hocico en la parte ventral hasta la \\r\\ngarganta y en la parte dorsal hasta la mitad del nasal tiene cerdas blanquecinas; otra característica única \\r\\nde la piel es la presencia de una glándula con olor localizada en la parte media del dorso.', 'Se encuentra en bosques tropicales húmedos, sabanas y bosques secos, requiriendo grandes extensiones de terreno para su desplazamiento. Vive en grandes manadas de hasta 100 individuos, lo que lo convierte en el único ungulado que forma grupos tan numerosos y actúan como dispersor de semillas y modifica el suelo al hozar en busca de alimento, contribuyendo a la regeneración del ecosistema. Tienen un período de gestación de aproximadamente 158 días. Los nacimientos pueden ocurrir tanto en la época de lluvias como en la temporada seca, dependiendo de la región. Las hembras pueden dar a luz entre 1 y 4 crías por camada, y si pierden una camada, pueden aparearse nuevamente y tener una segunda camada en el mismo año.', 'En Paraguay se encuentra especialmente en la región del Chaco Seco. Se ha registrado su presencia en el Departamento de Boquerón, en áreas con mayor cobertura boscosa. Tiene una distribución amplia en la región neotropical, desde el sureste de México hasta el norte de Argentina y el sur de Uruguay.', '', ''),
(53, NULL, 'Osito lavador', NULL, 'Procyon cancrivorus', 'img/lavador.jpg', 'Carnivora', 'Procyonidae', 'Soy un mamífero nocturno. Las hembras de mi especie son usualmente más pequeñas que los machos. Mi cabeza es ancha y redondeada y mis orejas son cortas. Mi pelaje tiene coloración grisácea, y mi rostro es de color blanco y con una mancha alrededor de los ojos asemejando un antifaz. Miden de 23 a 30 cm de altura, la longitud del cuerpo con la cabeza es de 42 a 70 cm y la de la cola de 20 a 41 cm. Pesan de 3 a 7 kg.', 'Prefiere zonas boscosas cercanas a ríos, arroyos y cuerpos de agua, ya que depende de estos ecosistemas para su alimentación. Es omnívoro, consumiendo cangrejos, peces, anfibios, moluscos, insectos y frutas. Es solitario, aunque puede formar pequeños grupos. Se caracteriza por su habilidad para trepar árboles y nadar, además de su peculiar hábito de \\\"lavar\\\" la comida antes de consumirla. Su período reproductivo varía según la región. La gestación dura entre 60 y 75 días, y las hembras pueden tener entre 2 y 7 crías, que permanecen en el refugio durante aproximadamente 6 semanas.', 'En Paraguay ha sido registrado principalmente en el Chaco paraguayo y el Bosque Atlántico, donde encuentra refugio en huecos de árboles y grietas de rocas. Cuenta con una distribución amplia en América Central y del Sur, desde Costa Rica hasta Argentina y Brasil.', '', ''),
(54, NULL, 'Pava Pintada', NULL, 'Crax fasciolata', 'img/istockphoto-1363298084-170667a.jpg', 'Galliformes', 'Cracidae', 'Ave de mediano tamaño llegando a medir hasta 85 cm y 2.8 kg, es muy similar a una pava doméstica\\r\\npero más esbelta y delgada. Presenta dimorfismo sexual, los machos son de color negro con vientre\\r\\ny punta de la cola blanco, pico negro con base amarilla, además tiene una cresta enrulada. La hembra\\r\\ncon dorso, pecho y cola barrados con negro y blanco, y el resto ventral color canela, presenta la misma\\r\\ncresta que el macho, pero matizada de negro y blanco. Sus patas son rosadas, su vuelo es bajo y de corta duración. Tienen un característico silbido y grito de advertencia. En las mañanas o en las tardes se pasea, por las orillas de los ríos, en el día busca semillas y frutas caídas en el piso del bosque.\\r\\n', 'Es frugívoro, consumiendo principalmente frutas grandes y carnosas. Es territorial y socialmente monógamo, viviendo solo o en parejas dentro del bosque. Nidifica en los árboles de mayor porte, y la hembra es la única encargada de la incubación. A pesar del cuidado parental, su éxito reproductivo es bajo. Tienen n ciclo reproductivo que varía según la región. Su temporada de reproducción ocurre en verano en la parte sur de su distribución. La incubación dura aproximadamente 30 días, y la hembra es la única encargada de este proceso, la hembra pone 2 huevos que incuban por 30 días. ', 'En Paraguay, su presencia se ha registrado en el Chaco Húmedo, donde se encuentra en áreas con vegetación densa y cuerpos de agua. También se distribuye en América del Sur, abarcando regiones de Brasil, Bolivia y Argentina. Prefieren bosques húmedos.', '', ''),
(55, NULL, 'Pecarí de collar', NULL, 'Dicotyles tajacu', 'img/Pecari_de_collar.jpg', 'Artiodactyla', 'Tayassuidae', 'Presenta una altura de medio metro en la cruz y una longitud de 70 a 110 cm y cola de 2 a 5 cm. Se caracteriza por un pelaje de cerdas castaño negruzcas y una mancha blanca que recuerda a un collar en la base del cuello. En el lomo tiene una cavidad glandular de 12 a 1 cm de la que secreta un aceite de olor almizclado.', 'Se encuentra en bosques tropicales y subtropicales, sabanas y zonas áridas, desde el nivel del mar hasta los 3,000 metros de altitud. Es omnívoro, consumiendo raíces, frutos, invertebrados y carroña. Vive en grupos de hasta 50 individuos, con una estructura social jerárquica. Su gestación dura entre 112 y 116 días, y las hembras pueden tener dos crías por camada.', 'En Paraguay se encuentra en diversas regiones, principalmente en bosques subtropicales, sabanas y montes xerófilos. Su presencia ha sido registrada en el Chaco paraguayo, donde habita en áreas con vegetación densa y acceso a fuentes de agua. También se encuentra en la Región Oriental, en zonas de transición entre bosques húmedos y áreas más abiertas. En Sudamérica, su presencia es notable en Brasil, Bolivia, Paraguay y Argentina.', '', ''),
(56, 4, 'Cobra falsa de agua', 'Ñacaniná', 'Hydrodynastes gigas', 'img/CobraDeAguaFalsa.jpg', 'Squamata', 'Colubridae', 'La cobra falsa de agua es una serpiente grande que puede alcanzar hasta 2,5 metros de longitud. Su cuerpo es robusto, con una coloración variable que va del marrón al oliva, salpicada de manchas oscuras que le brindan camuflaje entre la vegetación acuática. Presenta la notable capacidad de aplanar su cuello y levantar la parte anterior del cuerpo para imitar a una cobra verdadera, lo que utiliza como estrategia para intimidar a posibles depredadores.', 'Es una especie fuertemente asociada a ambientes acuáticos como ríos, lagunas, esteros y bañados, donde pasa gran parte del tiempo cazando o desplazándose. De hábitos principalmente diurnos, es una excelente nadadora y buceadora. Su dieta es amplia e incluye peces, anfibios, aves acuáticas y pequeños mamíferos, mostrando gran adaptabilidad en la búsqueda de alimento.', 'Se distribuye ampliamente por gran parte de Sudamérica, incluyendo Paraguay, el sur y centro de Brasil, el noreste de Argentina, Bolivia y Uruguay. Suele encontrarse en zonas con abundante agua y vegetación ribereña, y es común en los ecosistemas húmedos del Chaco y la región Oriental de Paraguay.', '', ''),
(57, NULL, 'Chima Chima', 'Kiri Kiri', 'Milvago chimachima', 'img/ChimaChima.jpg', 'Falconiformes', 'Falconidae', 'El chima chima o caracara cabeciamarillo es un ave rapaz de tamaño mediano, con una longitud aproximada de 40 cm. Presenta plumaje predominantemente pardo con un notable contraste en la cabeza, que es de color amarillento o crema. Su pico es fuerte y ligeramente curvado, adaptado para desgarrar. Las patas son robustas y amarillas. Tiene un vuelo lento y poco elegante, y suele ser visto caminando o posado, más que en pleno vuelo.', 'Es un ave oportunista y carroñera, aunque también caza presas pequeñas. Se alimenta de insectos, pequeños reptiles, mamíferos, aves y carroña. Es común verlo posado sobre el ganado para alimentarse de garrapatas, lo que le ha valido el nombre de “halcón garrapatero”. Prefiere áreas abiertas o semiabiertas como sabanas, bordes de bosques, pastizales y campos con ganado. Su comportamiento es menos agresivo que el de otras rapaces y suele ser tolerante a la presencia humana.', 'Se distribuye ampliamente en América del Sur y parte de América Central. En Paraguay está presente tanto en la región Oriental como en el Chaco, siendo un ave común en hábitats con vegetación baja o dispersa, y especialmente en paisajes modificados por el hombre, como campos de cultivo y estancias ganaderas.', '', ''),
(58, NULL, 'Lechuzón orejudo', 'Ñakurutu\'i. ', 'Asio clamator', 'img/lechuzonOrejudo.jpg', 'Strigiformes', 'Strigidae', 'El lechuzón orejudo es una lechuza de gran tamaño, que mide entre 40 y 46 cm de longitud. Su plumaje es predominantemente ocre y beige, con manchas y barras oscuras que le proporcionan un excelente camuflaje en los árboles. Posee penachos largos en la cabeza que semejan orejas, los cuales se levantan cuando el ave se siente en alerta. Sus ojos son grandes y de color amarillo, ideales para la visión nocturna, y su disco facial ayuda a captar mejor los sonidos.', 'Es un cazador nocturno y crepuscular, que suele capturar sus presas desde un posadero o mediante vuelos bajos y silenciosos. Su dieta está compuesta principalmente por roedores, pero también consume aves pequeñas, insectos grandes, ranas y reptiles. Habita una variedad de ambientes abiertos y semiabiertos, como sabanas, campos, bordes de bosques y áreas agrícolas, y se adapta a paisajes modificados por la actividad humana.', 'Su distribución abarca desde México hasta el centro y sur de Sudamérica. En Paraguay está presente en las dos regiones (Oriental y Occidental), siendo común en campos, sabanas, pastizales, esteros y áreas de cultivos, donde encuentra refugio y alimento con facilidad.', '', ''),
(59, NULL, 'Puma', 'Jagua pytã', 'Puma concolor', 'img/Puma.jpg', 'Carnivora', 'Felidae', 'El puma es un gran felino de cuerpo esbelto y musculoso, con pelaje corto que varía del gris amarillento al rojizo, y en ocasiones casi negro. Puede medir entre 1.2 y 2.4 metros de largo, incluida la cola, y pesar entre 30 y 90 kg. Su cabeza es redondeada con orejas cortas y redondeadas, y posee gran agilidad y fuerza para la caza. Es un cazador solitario y sigiloso, capaz de adaptarse a diversos ecosistemas.', 'El puma es un depredador ápice que se alimenta principalmente de mamíferos medianos a grandes, como ciervos, pecaríes, roedores y aves. Tiene hábitos solitarios y territoriales, con actividad variable que puede ser diurna o nocturna según la presión humana y la disponibilidad de presas. Habita desde bosques tropicales hasta áreas montañosas, adaptándose a distintos climas y condiciones.', 'Se encuentra en casi toda América desde Canadá hasta el sur de Argentina. En Paraguay está presente tanto en la región Oriental como en el Chaco, siendo una especie clave en el equilibrio de los ecosistemas naturales. Su presencia ha disminuido en algunas zonas debido a la pérdida de hábitat y la cacería, pero sigue siendo un símbolo emblemático de la fauna sudamericana.', '', ''),
(60, NULL, 'Papagayo rojo', 'Gua\'a pytã', 'Ara chloropterus', 'img/PapagayoRojo.jpg', 'Psittaciformes', 'Psittacidae', 'El papagayo rojo es uno de los guacamayos más grandes de Sudamérica, alcanzando hasta 95 cm de longitud, incluida su larga y elegante cola. Su plumaje es de un rojo intenso en la mayor parte del cuerpo, con plumas verdes en las alas y azul en la parte externa de las mismas. El rostro es blanco y desnudo, con líneas de pequeñas plumas rojas alrededor de los ojos. Su pico es grande y curvado, de color marfil en la parte superior, adaptado para romper frutos duros y semillas.', 'Es un ave social que suele desplazarse en parejas o grupos familiares, y en ocasiones en bandadas más grandes. Se alimenta de una gran variedad de frutos, semillas, nueces y flores, desempeñando un papel importante en la dispersión de semillas en los bosques. Prefiere bosques húmedos, galerías de ríos y áreas con grandes árboles, donde encuentra sitios para anidar y descansar. Su vuelo es fuerte y ruidoso, y sus llamados son potentes y característicos.', 'Se distribuye en una amplia región de América del Sur, desde Panamá hasta el norte de Argentina. En Paraguay habita principalmente en la región Oriental, en bosques de la ecorregión del Alto Paraná y en zonas de selvas y bosques de galería. Aunque su población ha disminuido por la pérdida de hábitat y la captura ilegal, todavía puede encontrarse en áreas protegidas y regiones con buen estado de conservación.', '', ''),
(61, 12, 'Cotorra Cabeza Negra', NULL, 'Aratinga nenday', 'img/Aratinga-nenday-1.jpg', 'Psittaciformes', 'Psittacidae', 'La cotorra ñanday, también conocida como perico ñanday o cotorra cabeza negra, es una especie de ave originaria de América del Sur. Mide entre 27 y 30 centímetros de largo y pesa aproximadamente 140 gramos. Su plumaje es predominantemente verde, pero presenta una distintiva cabeza negra que le da su nombre común. Sus alas tienen plumas de vuelo negras, la cola es larga con tonos azulados en la punta, y los muslos están cubiertos por plumas rojas. El pecho superior tiene un tono verde azulado, mientras que el inferior es de un verde más claro. Los ejemplares jóvenes son muy parecidos a los adultos, aunque con menos azul en el pecho y una cola más corta.', 'Esta especie habita principalmente en bosques de galería, bordes de bosques secos, sabanas, palmares y áreas abiertas, hasta altitudes de aproximadamente 800 metros. Es una cotorra muy sociable que suele formar bandadas grandes, especialmente fuera de la época de cría. Su dieta es bastante variada e incluye semillas, frutas, bayas, flores, brotes y nueces de palma. A menudo se alimenta tanto en árboles como en el suelo, y también se la puede ver visitando comederos urbanos. En algunas regiones agrícolas, se la considera plaga por alimentarse de cultivos. Para reproducirse, utiliza cavidades en árboles o postes, donde la hembra pone entre 3 y 5 huevos. Estos son incubados durante unas 24 a 26 días, y los polluelos empluman entre las 7 y 8 semanas de vida.', 'La distribución natural de la cotorra ñanday abarca el sudeste de Bolivia, el suroeste de Brasil, el centro de Paraguay y el norte de Argentina, principalmente en zonas cercanas al Pantanal. Sin embargo, debido a escapes o liberaciones, existen poblaciones establecidas fuera de su rango original, como en algunas zonas de Estados Unidos (especialmente en Florida, California y Texas), así como en Israel y en la isla de Tenerife.\\r\\nEn cuanto a su apariencia, es fácil de reconocer por su cabeza negra contrastando con el verde del cuerpo, su cola larga azulada y los muslos con plumas rojas. Estas características la convierten en una de las cotorras más distintivas de la región.', '', ''),
(62, 2, 'Gorrión común', NULL, 'Passer domesticus', 'img/gorrioncomun.jpg', 'Passeriformes', 'Passeridae', 'El gorrión común es un ave pequeña que mide entre 13 y 17 centímetros de longitud y pesa de 24 a 39 gramos. Presenta dimorfismo sexual: el macho tiene una corona gris, mejillas blancas, babero negro y dorso pardo rojizo con manchas, mientras que la hembra y los juveniles tienen un plumaje más apagado, en tonos marrón grisáceos, con listas y una línea clara sobre el ojo. Su pico es corto, robusto y cónico, adaptado para triturar semillas.', 'Se adapta fácilmente a ambientes humanizados, ya sean urbanos, suburbanos o rurales. Anida en cavidades de edificios, postes, tejados, nidos abandonados u orificios naturales. Construye sus nidos con hierbas, plumas, papeles y cualquier tipo de material disponible. Puede tener varias puestas al año, generalmente de 3 a 6 huevos, que son incubados por ambos padres durante unos 10 a 14 días. Los pichones abandonan el nido a las dos semanas. Se alimenta principalmente de semillas, granos, restos de comida humana e insectos (sobre todo en época de cría). Su comportamiento es gregario, desplazándose y alimentándose en grupos.', 'Es originario de Europa, Asia y el norte de África, pero ha sido introducido exitosamente en América, Australia, Nueva Zelanda y otras regiones. Actualmente es una de las aves más comunes y extendidas del mundo. Se adapta a casi cualquier clima, siempre que haya presencia humana. En zonas urbanas y rurales es muy frecuente, y a menudo compite con otras aves por lugares de nidificación.', '', ''),
(63, 2, 'Tucán toco', NULL, 'Ramphastos toco', 'img/Toco_Toucan_.jpg', 'Piciformes', 'Ramphastidae', 'El tucán toco es el miembro más grande de su familia, alcanzando unos 60–64cm de longitud total y un peso entre 600 y 760g. Su plumaje es negro, salvo la garganta y pecho blancos, y la región bajo la cola muestra tonos rojos. Su característica más notable es el enorme pico amarillo-anaranjado con una mancha negra en la punta; este pico puede medir hasta 20cm, lo que representa casi la mitad de su longitud total, aunque es sorprendentemente ligero y resistente gracias a su estructura hueca y esponjosa.', 'Vive en pequeños grupos de alrededor de seis individuos y es un ave muy social, empleando su gran pico no solo para alimentarse sino también para regular su temperatura corporal. Aunque su dieta es principalmente frugívora, este tucán también ingiere insectos, pequeños reptiles y ocasionalmente huevos y crías de otras aves. Anida en cavidades de árboles, donde la hembra deposita entre 2 y 4 huevos, los cuales incuban ambos padres durante unas 17 a 20 semanas, y los polluelos tardan unas 6 a 9 semanas en abandonar el nido.', 'Es endémico de Sudamérica, con presencia desde las Guayanas hasta el norte de Argentina y Uruguay. Se lo encuentra principalmente en ecosistemas semiabiertos como sabanas, bosques galería, el Cerrado brasileño y la región del Pantanal, habitando desde zonas de llanura hasta altitudes de 1750m. Su rango se ha expandido hacia el sur en las últimas décadas.', '', ''),
(64, NULL, 'Pitón tigrina', NULL, 'Python molurus', 'img/Piton_Tigrina.jpg', 'Squamata', 'Pythonidae', 'La pitón tigrina es una serpiente constrictora de gran tamaño que puede alcanzar entre 3 y 6 metros de longitud, aunque rara vez supera los 5 metros. Su cabeza es triangular y relativamente pequeña en proporción al cuerpo. Presenta un patrón de manchas oscuras sobre un fondo claro, lo que le da su nombre distintivo. Carece de veneno y utiliza potentes músculos para estrangular a sus presas. Posee sensores de calor en la mandíbula que le permiten localizar presas de sangre caliente.', 'Esta especie es nocturna y semiacuática, frecuentando humedales, áreas cercanas a ríos, pantanos y arrozales, aunque también se adapta a bosques y zonas rurales. Su dieta varía según la edad: los juveniles se alimentan de roedores, lagartijas y crías de aves, mientras que los adultos pueden capturar presas más grandes, como ciervos jóvenes, cerdos, monos e incluso cocodrilos pequeños. Es una madre protectora: la hembra puede poner entre 15 y 100 huevos y los incuba entre 50 y 90 días, enrollándose alrededor para regular su temperatura haciendo contracciones musculares.', 'Se distribuye naturalmente en el sudeste asiático: India, Myanmar, Tailandia, Vietnam, Malasia e islas adyacentes. También hay poblaciones introducidas en otras áreas. Prefiere hábitats cálidos y húmedos, principalmente en las inmediaciones del agua.', '', ''),
(65, NULL, 'Saria Pata Roja', NULL, 'Cariama cristata', 'img/patasrojas.jpg', 'Cariamiformes', 'Cariamidae', 'La Saria de patas rojas es un ave terrestre de gran porte, midiendo entre 75 y 90cm de altura y pesando alrededor de 1,5 a 2,2kg. Su plumaje es pardo-grisáceo manchado de tonos oscuros, con el vientre más claro. Se caracteriza por poseer patas rojas y un pico también rojizo, así como una cresta de plumas erizadas en la cabeza justo encima del pico. Sus ojos de color amarillo destacan sobre el rostro y la cola presenta una banda negra antes de la punta blanca.', 'Es una especie diurna y terrestre que prefiere caminar o correr —llega a alcanzar hasta 25km/h— antes que volar. Habita pastizales, sabanas y cerrados, evadiendo zonas anegadas y bosques densos. Su dieta es carnívora: consume insectos (como saltamontes), reptiles pequeños, roedores, e incluso serpientes. Se mueve en solitario, parejas o pequeños grupos familiares. Anida en ramas de árboles o en el suelo, poniendo de 2 a 4 huevos en nidos cien por ciento construidos con ramitas y forrados con hojas secas o estiércol de ganado. ', 'Su área natural abarca gran parte de Sudamérica: se distribuye por Brasil central y oriental, Paraguay, Bolivia, Uruguay, Argentina (hasta La Pampa) y sur del Amazonas. Se estima que ocupa unos 5,9 millones de km².', '', ''),
(67, NULL, 'Serpiente de leche	', ' Culebra de Leche', 'Lampropeltis triangulum', 'img/Lampropeltis-triangulum-sinaloae-013.jpg', 'Squamata', 'Colubridae', 'La serpiente de leche de Sinaloa es predominantemente de color rojo sangre con distintos anillos o bandas de color negro que tienen bandas más delgadas de color crema, blanquecino o (rara vez) amarillo crema claro dentro de las bandas negras.[', 'Es una serpiente no venenosa y constrictora.\\r\\nSe alimenta de pequeños roedores, aves, huevos, lagartijas y otras serpientes (incluso venenosas, ya que es inmune a algunas toxinas).\\r\\nEs de hábitos nocturnos o crepusculares.', 'Amplia distribución en América, desde Canadá hasta norte de Sudamérica.', '', ''),
(68, 3, ' Conejo común', 'Conejo Europeo', 'Oryctolagus cuniculus', 'img/images (3).jpeg', ' Lagomorpha', 'Leporidae', 'El conejo común o conejo europeo (Oryctolagus cuniculus) es una especie de mamífero lagomorfo de la familia Leporidae, y el único miembro actual del género Oryctolagus. Mide hasta 50 cm y su masa puede ser hasta 2.5 kg. ', 'Es un herbívoro generalista, se alimenta principalmente de pastos, hierbas, brotes, corteza y raíces.\\r\\nEs una especie clave en muchos ecosistemas: su pastoreo influye en la estructura de la vegetación, y sirve de presa para numerosos carnívoros.\\r\\nVive en madrigueras subterráneas llamadas conejeras, organizadas en colonias.', 'Europa continental, Australia, Nueva Zelanda, América del Sur y América del Norte.\\r\\nHabita praderas, matorrales, bosques abiertos y áreas agrícolas.', '', ''),
(69, 3, 'Pato criollo', 'Pato Moscovita', 'Cairina moschata', 'img/Screenshot_20250614_224622_Google.jpg', ' Anseriformes', 'Anatidae', 'Tamaño: 66–84 cm de longitud; los machos son notablemente más grandes que las hembras.\\r\\nPlumaje: generalmente negro con reflejos verdosos y partes blancas; las variedades domésticas pueden ser blancas, moteadas o de color uniforme.\\r\\nCabeza y cara con carúnculas rojas (protuberancias carnosas) alrededor del pico y ojos.\\r\\nVuelo pesado, pero pueden posarse en árboles gracias a sus fuertes garras.', 'Es un pato silvestre y doméstico: existen poblaciones salvajes y variedades criadas en granjas.\\r\\nEs omnívoro: consume plantas acuáticas, insectos, crustáceos, pequeños peces y materia orgánica.', 'Originario de Centro y Sudamérica, desde México hasta el norte de Argentina y Uruguay.', '', ''),
(70, 3, 'Pavo real común ', 'pavo real de la India ', 'Pavo cristatus', 'img/images (5).jpeg', 'Galliformes  ', 'Phasianidae', 'El pavo real es una especie con un fuerte dimorfismo sexual. El macho de esta especie tiene una longitud de entre 100-115 cm del pico a la cola, alcanzando los 195-225 cm hasta el extremo de las largas plumas especializadas que conforman el abanico cola secundaria cuando están plenamente desarrolladas. Su peso es de 4-6 kg. La hembra es más pequeña, con una longitud de unos 95 cm y un peso de 2,75-4 kg.', 'Es un ave omnívora: se alimenta de semillas, frutas, insectos, pequeños reptiles y pequeños mamíferos.\\r\\nVive en bosques abiertos, zonas de matorrales y áreas agrícolas, generalmente cerca de asentamientos humanos.', 'Originario del subcontinente indio: India, Sri Lanka, Pakistán y zonas adyacentes.', '', ''),
(71, NULL, 'Ganso', 'Guarimbe', 'Anser anser', 'img/ganso.jpg', 'Anseriformes', 'Anatidae', 'Ave acuática de tamaño mediano a grande, cuello largo, patas palmeadas y pico ancho. Suele ser de color blanco, gris o marrón', 'Vive en humedales, lagos y ríos. Se alimenta de plantas acuáticas, hierbas y pequeños invertebrados', 'Ampliamente distribuido en Europa, Asia y Norteamérica; también introducido en otras regiones', '', ''),
(72, NULL, 'Tigre de Bengala', 'Yaguarete', 'Panthera tigris tigris', 'img/tigre_de_bengala.jpg', 'Carnivora', 'Felidae', 'El mayor felino del mundo, con pelaje naranja y rayas negras, vientre blanco y poderosas mandíbulas', 'Habita en bosques, manglares y sabanas. Es un superdepredador que caza ciervos, búfalos y otros mamíferos', 'Principalmente en India, Bangladesh, Nepal y Bután', '', ''),
(73, NULL, 'Gavilán Común', 'Taguató', 'Rupornis magnirostris', 'img/gavilan.jpg', 'Accipitriformes', 'Accipitridae', 'Ave rapaz mediana, con alas anchas, cola corta y patas amarillas. Coloración parda con pecho barrado', 'Caza pequeños mamíferos, aves, reptiles e insectos. Vive en bosques, sabanas y áreas abiertas', 'Desde México hasta Argentina, presente en Paraguay y gran parte de Sudamérica', '', ''),
(74, NULL, 'Tortuga Terrestre', 'Karumbe', 'Chelonoidis denticulata', 'img/\r\nTortuga_terrestre_amazónica.jpg', 'Testudines', 'Testudinidae', 'Tortuga grande con caparazón abombado, patas robustas y escamas amarillas o anaranjadas en las extremidades', 'Herbívora, se alimenta de frutas, hojas y flores. Habita en selvas tropicales', 'Cuenca del Amazonas (Brasil, Perú, Colombia, Venezuela, etc.)', '', ''),
(75, 5, 'Urraca copetona', 'Aka\\\'ê paramî', 'Cyanocorax cristatellus', 'img/urraca_copetona.jpg', 'Passeriformes', 'Corvidae ', 'Ave de tamaño mediano, plumaje negro brillante con vientre blanco y una distintiva cresta erecta en la cabeza, con ojos amarillos intensos y pico fuerte', 'Se alimenta de frutas, insectos, huevos de otras aves y pequeños vertebrados. Muy social, forma bandadas ruidosas y es territorial. Habita en bosques, sabanas y áreas semiabiertas', 'Presente en Brasil, Paraguay, Bolivia y el norte de Argentina', '', '');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `especies`
--
ALTER TABLE `especies`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `especies`
--
ALTER TABLE `especies`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=77;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
